# Generated by Django 4.2.16 on 2025-04-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the AI assistant', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('voice', models.CharField(choices=[('alloy', 'Alloy - Neutral, professional, versatile'), ('shimmer', 'Shimmer - Warm, welcoming, clear'), ('nova', 'Nova - Confident, nurturing, thoughtful'), ('echo', 'Echo - Warm, resonant, confident'), ('fable', 'Fable - Deep, authoritative, wise'), ('onyx', 'Onyx - Smooth, confident, professional')], default='nova', max_length=20)),
                ('greeting_message', models.TextField(default="Hello! I'm your course assistant. How can I help you today?", help_text='Message to greet students when they first connect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retell_agent_id', models.CharField(blank=True, help_text='RetellAI agent ID for this assistant', max_length=255, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='AIAssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai_assistant.aiassistant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiassistantconversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
